// ===================================================================
// POWER QUERY M SCRIPTS FOR BERLIN AIRBNB DATA
// ===================================================================
// Copy these scripts into Power Query Editor for automated data loading

// ===================================================================
// 1. MAIN LISTINGS DATA CONNECTION
// ===================================================================

let
    // Define the source path - Update this path to match your data location
    SourcePath = "C:\Projects\DataScience\Portfolio\Airbnb-EDA-Berlin\Workspace\airbnb-eda-berlin\data\AirBnB-Berlin\2025-06-20\listings_cleaned.csv",
    
    // Load the CSV file
    Source = Csv.Document(File.Contents(SourcePath),[Delimiter=",", Columns=null, Encoding=65001, QuoteStyle=QuoteStyle.None]),
    
    // Promote headers
    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    
    // Define data types for key columns
    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders,{
        {"id", Int64.Type},
        {"listing_url", type text},
        {"scrape_id", Int64.Type},
        {"last_scraped", type date},
        {"source", type text},
        {"name", type text},
        {"description", type text},
        {"neighborhood_overview", type text},
        {"picture_url", type text},
        {"host_id", Int64.Type},
        {"host_url", type text},
        {"host_name", type text},
        {"host_since", type date},
        {"host_location", type text},
        {"host_about", type text},
        {"host_response_time", type text},
        {"host_response_rate", type text},
        {"host_acceptance_rate", type text},
        {"host_is_superhost", type text},
        {"host_thumbnail_url", type text},
        {"host_picture_url", type text},
        {"host_neighbourhood", type text},
        {"host_listings_count", Int64.Type},
        {"host_total_listings_count", Int64.Type},
        {"host_verifications", type text},
        {"host_has_profile_pic", type text},
        {"host_identity_verified", type text},
        {"neighbourhood", type text},
        {"neighbourhood_cleansed", type text},
        {"neighbourhood_group_cleansed", type text},
        {"latitude", type number},
        {"longitude", type number},
        {"property_type", type text},
        {"room_type", type text},
        {"accommodates", Int64.Type},
        {"bathrooms_text", type text},
        {"bedrooms", Int64.Type},
        {"beds", Int64.Type},
        {"amenities", type text},
        {"price", Currency.Type},
        {"minimum_nights", Int64.Type},
        {"maximum_nights", Int64.Type},
        {"minimum_minimum_nights", Int64.Type},
        {"maximum_minimum_nights", Int64.Type},
        {"minimum_maximum_nights", Int64.Type},
        {"maximum_maximum_nights", Int64.Type},
        {"minimum_nights_avg_ntm", type number},
        {"maximum_nights_avg_ntm", type number},
        {"calendar_updated", type text},
        {"has_availability", type text},
        {"availability_30", Int64.Type},
        {"availability_60", Int64.Type},
        {"availability_90", Int64.Type},
        {"availability_365", Int64.Type},
        {"calendar_last_scraped", type date},
        {"number_of_reviews", Int64.Type},
        {"number_of_reviews_ltm", Int64.Type},
        {"number_of_reviews_l30d", Int64.Type},
        {"first_review", type date},
        {"last_review", type date},
        {"review_scores_rating", type number},
        {"review_scores_accuracy", type number},
        {"review_scores_cleanliness", type number},
        {"review_scores_checkin", type number},
        {"review_scores_communication", type number},
        {"review_scores_location", type number},
        {"review_scores_value", type number},
        {"license", type text},
        {"instant_bookable", type text},
        {"calculated_host_listings_count", Int64.Type},
        {"calculated_host_listings_count_entire_homes", Int64.Type},
        {"calculated_host_listings_count_private_rooms", Int64.Type},
        {"calculated_host_listings_count_shared_rooms", Int64.Type},
        {"reviews_per_month", type number}
    }),
    
    // Clean text fields - remove line breaks and extra spaces
    CleanedText = Table.TransformColumns(ChangedTypes, {
        {"name", each Text.Clean(Text.Trim(_))},
        {"description", each if _ <> null then Text.Clean(Text.Trim(_)) else null},
        {"neighborhood_overview", each if _ <> null then Text.Clean(Text.Trim(_)) else null},
        {"host_name", each if _ <> null then Text.Clean(Text.Trim(_)) else null},
        {"host_about", each if _ <> null then Text.Clean(Text.Trim(_)) else null}
    }),
    
    // Add calculated columns
    AddedColumns = Table.AddColumn(CleanedText, "neighbourhood_group", each 
        if [neighbourhood_group_cleansed] <> null then [neighbourhood_group_cleansed] 
        else "Unknown"
    ),
    
    // Add price category column
    AddedPriceCategory = Table.AddColumn(AddedColumns, "price_category", each 
        if [price] <= 50 then "Budget (≤€50)"
        else if [price] <= 100 then "Mid-range (€51-€100)"
        else if [price] <= 200 then "Premium (€101-€200)"
        else "Luxury (€200+)"
    ),
    
    // Add occupancy rate column
    AddedOccupancyRate = Table.AddColumn(AddedPriceCategory, "occupancy_rate", each 
        if [availability_365] <> null then (365 - [availability_365]) / 365 else null
    ),
    
    // Add district category
    AddedDistrictCategory = Table.AddColumn(AddedOccupancyRate, "district_category", each 
        if [neighbourhood_group] = "Mitte" or [neighbourhood_group] = "Friedrichshain-Kreuzberg" then "Central Berlin"
        else if [neighbourhood_group] = "Pankow" or [neighbourhood_group] = "Reinickendorf" then "North Berlin"
        else if [neighbourhood_group] = "Charlottenburg-Wilmersdorf" or [neighbourhood_group] = "Spandau" then "West Berlin"
        else if [neighbourhood_group] = "Neukölln" or [neighbourhood_group] = "Tempelhof-Schöneberg" then "South Berlin"
        else if [neighbourhood_group] = "Steglitz-Zehlendorf" then "Southwest Berlin"
        else if [neighbourhood_group] = "Marzahn-Hellersdorf" or [neighbourhood_group] = "Lichtenberg" then "East Berlin"
        else if [neighbourhood_group] = "Treptow-Köpenick" then "Southeast Berlin"
        else "Other"
    ),
    
    // Filter out extreme outliers and invalid data
    FilteredData = Table.SelectRows(AddedDistrictCategory, each 
        [price] <> null and [price] > 0 and [price] < 1000 and
        [latitude] <> null and [longitude] <> null and
        [latitude] > 52.3 and [latitude] < 52.7 and
        [longitude] > 13.0 and [longitude] < 13.8
    )
in
    FilteredData

// ===================================================================
// 2. NEIGHBOURHOODS DATA CONNECTION
// ===================================================================

let
    // Define the source path
    SourcePath = "C:\Projects\DataScience\Portfolio\Airbnb-EDA-Berlin\Workspace\airbnb-eda-berlin\data\AirBnB-Berlin\2025-06-20\neighbourhoods.csv",
    
    // Load the CSV file
    Source = Csv.Document(File.Contents(SourcePath),[Delimiter=",", Columns=null, Encoding=65001, QuoteStyle=QuoteStyle.None]),
    
    // Promote headers
    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    
    // Define data types
    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders,{
        {"neighbourhood_group", type text},
        {"neighbourhood", type text}
    }),
    
    // Clean text data
    CleanedText = Table.TransformColumns(ChangedTypes, {
        {"neighbourhood_group", each Text.Clean(Text.Trim(_))},
        {"neighbourhood", each Text.Clean(Text.Trim(_))}
    })
in
    CleanedText

// ===================================================================
// 3. REVIEWS DATA CONNECTION (Optional - for detailed analysis)
// ===================================================================

let
    // Define the source path
    SourcePath = "C:\Projects\DataScience\Portfolio\Airbnb-EDA-Berlin\Workspace\airbnb-eda-berlin\data\AirBnB-Berlin\2025-06-20\reviews.csv",
    
    // Load the CSV file
    Source = Csv.Document(File.Contents(SourcePath),[Delimiter=",", Columns=null, Encoding=65001, QuoteStyle=QuoteStyle.None]),
    
    // Promote headers
    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    
    // Define data types
    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders,{
        {"listing_id", Int64.Type},
        {"id", Int64.Type},
        {"date", type date},
        {"reviewer_id", Int64.Type},
        {"reviewer_name", type text},
        {"comments", type text}
    }),
    
    // Clean comments field
    CleanedComments = Table.TransformColumns(ChangedTypes, {
        {"comments", each if _ <> null then Text.Clean(Text.Trim(_)) else null},
        {"reviewer_name", each if _ <> null then Text.Clean(Text.Trim(_)) else null}
    }),
    
    // Add date-based columns
    AddedDateColumns = Table.AddColumn(CleanedComments, "review_year", each Date.Year([date])),
    AddedMonthColumn = Table.AddColumn(AddedDateColumns, "review_month", each Date.Month([date])),
    AddedQuarterColumn = Table.AddColumn(AddedMonthColumn, "review_quarter", each Date.QuarterOfYear([date])),
    
    // Filter for relevant date range (last 3 years)
    FilteredByDate = Table.SelectRows(AddedQuarterColumn, each [date] >= Date.AddYears(DateTime.Date(DateTime.LocalNow()), -3))
in
    FilteredByDate

// ===================================================================
// 4. CALENDAR DATA CONNECTION (if available)
// ===================================================================

let
    // Define the source path - update if calendar.csv is available
    SourcePath = "C:\Projects\DataScience\Portfolio\Airbnb-EDA-Berlin\Workspace\airbnb-eda-berlin\data\AirBnB-Berlin\2025-06-20\calendar.csv",
    
    // Check if file exists, if not return empty table
    Source = try Csv.Document(File.Contents(SourcePath),[Delimiter=",", Columns=null, Encoding=65001, QuoteStyle=QuoteStyle.None])
             otherwise #table({"listing_id", "date", "available", "price"}, {}),
    
    // Only proceed if we have data
    Result = if Table.RowCount(Source) > 0 then
        let
            // Promote headers
            PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
            
            // Define data types
            ChangedTypes = Table.TransformColumnTypes(PromotedHeaders,{
                {"listing_id", Int64.Type},
                {"date", type date},
                {"available", type text},
                {"price", type text}
            }),
            
            // Clean price field (remove $ and convert to number)
            CleanedPrice = Table.TransformColumns(ChangedTypes, {
                {"price", each if _ <> null and _ <> "" then 
                    try Number.From(Text.Replace(Text.Replace(_, "$", ""), ",", "")) otherwise null 
                    else null}
            }),
            
            // Convert price to proper currency type
            ConvertedPrice = Table.TransformColumnTypes(CleanedPrice, {{"price", Currency.Type}}),
            
            // Add date-based columns
            AddedDateColumns = Table.AddColumn(ConvertedPrice, "year", each Date.Year([date])),
            AddedMonthColumn = Table.AddColumn(AddedDateColumns, "month", each Date.Month([date])),
            AddedDayOfWeek = Table.AddColumn(AddedMonthColumn, "day_of_week", each Date.DayOfWeek([date])),
            AddedWeekend = Table.AddColumn(AddedDayOfWeek, "is_weekend", each [day_of_week] = 0 or [day_of_week] = 6),
            
            // Filter for reasonable price range
            FilteredData = Table.SelectRows(AddedWeekend, each 
                [price] = null or ([price] > 0 and [price] < 1000)
            )
        in
            FilteredData
    else
        Source
in
    Result

// ===================================================================
// 5. DATA QUALITY AND VALIDATION FUNCTIONS
// ===================================================================

// Function to validate coordinates are within Berlin bounds
let
    ValidateBerlinCoordinates = (latitude as number, longitude as number) =>
        latitude >= 52.3 and latitude <= 52.7 and longitude >= 13.0 and longitude <= 13.8
in
    ValidateBerlinCoordinates

// Function to clean and validate price data
let
    CleanPriceData = (priceText as text) =>
        let
            // Remove currency symbols and commas
            CleanedText = Text.Replace(Text.Replace(Text.Replace(priceText, "$", ""), "€", ""), ",", ""),
            // Convert to number
            PriceNumber = try Number.From(CleanedText) otherwise null,
            // Validate range
            ValidatedPrice = if PriceNumber <> null and PriceNumber > 0 and PriceNumber < 1000 
                           then PriceNumber 
                           else null
        in
            ValidatedPrice
in
    CleanPriceData

// ===================================================================
// 6. DIMENSION TABLES
// ===================================================================

// Room Type Dimension
let
    RoomTypes = #table(
        {"room_type", "room_type_category", "room_type_sort_order"},
        {
            {"Entire home/apt", "Private", 1},
            {"Private room", "Shared", 2},
            {"Shared room", "Shared", 3},
            {"Hotel room", "Commercial", 4}
        }
    )
in
    RoomTypes

// Price Category Dimension
let
    PriceCategories = #table(
        {"price_category", "price_min", "price_max", "sort_order"},
        {
            {"Budget (≤€50)", 0, 50, 1},
            {"Mid-range (€51-€100)", 51, 100, 2},
            {"Premium (€101-€200)", 101, 200, 3},
            {"Luxury (€200+)", 201, 9999, 4}
        }
    )
in
    PriceCategories

// District Category Dimension
let
    DistrictCategories = #table(
        {"district_category", "district_description", "is_central", "sort_order"},
        {
            {"Central Berlin", "Prime locations in city center", true, 1},
            {"North Berlin", "Residential areas north of center", false, 2},
            {"West Berlin", "Western districts and suburbs", false, 3},
            {"South Berlin", "Southern districts", false, 4},
            {"Southwest Berlin", "Upscale southwestern area", false, 5},
            {"East Berlin", "Eastern districts", false, 6},
            {"Southeast Berlin", "Southeastern area", false, 7},
            {"Other", "Other areas", false, 8}
        }
    )
in
    DistrictCategories

// ===================================================================
// END OF POWER QUERY M SCRIPTS
// ===================================================================